### ISSUE TITLE
sound quality.

### ISSUE THREAD

**Issue by arnauldb** [billw2/pikrellcam#28]
Hello,

I've been using pikrellcam for two weeks, I use it to record squirrels and birds in my garden, and it is working great. I'm wondering if there is a way to play with the sound quality, and how? Also, would you recommend any usb mic, as, for now, there is a lot of "noise" recorded in the video and I have to clean it in audacity to get a decent/clear sound?

Thank you,

**Comment by arnauldb** [comment]
I found a good usb mic and the sound is good now.

**Comment by Yves911** [comment]
@arnauldb hi, can you share which mic are you using now with good results?

**Comment by arnauldb** [comment]
>  can you share which mic are you using now with good results?

I bough the "CAD Audio U9 Condenser Microphone, Omni " on amazon: https://www.amazon.com/gp/offer-listing/B004P1BQG2/ref=dp_olp_all_mbc?ie=UTF8&condition=all

It is a usb mic, the results are good. To further reduce noise I also found out that it is better not to connect it directly to the raspberry pi (vibrations, ...?) but to use a short "extension cable USB 2.0, type A M/F" between the pi and mic: https://www.amazon.fr/Lindy-Rallonge-USB-2-0-noir/dp/B01LY6BGTC/ref=dp_ob_title_ce

Also, the mic has an illuminated red ring, which may be annoying....

The result: 

![2222](https://user-images.githubusercontent.com/13196747/27984358-c071d6da-63d4-11e7-8ab5-40dc7a9c05ec.jpg)

**Comment by Yves911** [comment]
Thanks, i just bought this one https://www.amazon.fr/gp/product/B01LCIGY8U/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1 
I don't expect too much from it... but let's see what i can achieve with this cheap mic.
