### ISSUE TITLE
nginx update broke pikrellcam

### ISSUE THREAD

**Issue by okazou57** [billw2/pikrellcam#40]
On november 11 I did an update to my raspbian, it consisted mostly of nginx updates. After that update, pikrellcam stoped working an I get the following message in journalctl when I try to start pikrellcam from the web interface: 
Nov 21 14:17:53 RPi-Salon sudo[1468]: www-data : TTY=unknown ; PWD=/home/pi/pikrellcam/www ; USER=pi ; COMMAND=/home/pi/pikrellcam/pikrellcam
Nov 21 14:17:53 RPi-Salon sudo[1468]: pam_unix(sudo:session): session opened for user pi by (uid=0)
Nov 21 14:17:53 RPi-Salon sudo[1492]: pam_unix(sudo:auth): conversation failed

I have been checking all permissions and made shure pi was member of www-data group, nothing worked any indication as to where I should be looking for?

**Comment by billw2** [comment]
On Wed, 21 Nov 2018 12:23:26 -0800
okazou57 <notifications@github.com> wrote:

> On november 11 I did an update to my raspbian, it consisted mostly of nginx updates. After that update,
> pikrellcam stoped working an I get the following message in journalctl when I try to start pikrellcam from
> the web interface :+1: Nov 21 14:17:53 RPi-Salon sudo[1468]: www-data : TTY=unknown ;
> PWD=/home/pi/pikrellcam/www ; USER=pi ; COMMAND=/home/pi/pikrellcam/pikrellcam Nov 21 14:17:53 RPi-Salon
> sudo[1468]: pam_unix(sudo:session): session opened for user pi by (uid=0) Nov 21 14:17:53 RPi-Salon
> sudo[1492]: pam_unix(sudo:auth): conversation failed
> 
> I have been checking all permissions and made shure pi was member of www-data group, nothing worked any
> indication as to where I should be looking for?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/billw2/pikrellcam/issues/40

The web interface runs as user www-data and needs sudo permission to run pikrellcam.  The error you get
seems to say www-data fails trying to do that.

1) can you run pikrellcam by hand from a terminal as user pi?  Just enter the "pikrellcam" command.

2) do you still have the file /etc/sudoers.d/pikrellcam with the line:
     www-data ALL=(pi) NOPASSWD: /home/pi/pikrellcam/pikrellcam

    If not, try a rerun of the pikrellcam install script.

**Comment by okazou57** [comment]
Thanks a lot!!! I did not have the www-data ALL=(pi) NOPASSWD: /home/pi/pikrellcam/pikrellcam in my sudoer file. I do not remember seeing that at any time. Most likely not caused by the nginx update. Every thing back to normal.
