### ISSUE TITLE
I've installed everything and cant click on anything

### ISSUE THREAD

**Issue by rcpilotp51** [billw2/pikrellcam#62]
I just got finished installing this on a raspberry pi 0 w and when going to the web interface nothing is responsive, meaning i click on something and nothing happens - especially with the image preview. is there anything further i need to do, thanks

~keith

**Comment by rcpilotp51** [comment]
The image preview isnt available im using a pi0w and a picam v1.3 i can use raspistill to take an image, yet there us no preview in the interface. I cant click on any of the buttons, or they dont seem to do anything

**Comment by billw2** [comment]
On Wed, 22 Jul 2020 05:31:04 -0700
Keith Brown <notifications@github.com> wrote:

> The image preview isnt available im using a pi0w and a picam v1.3 i can use raspistill to take an image, yet
> there us no preview in the interface. I cant click on any of the buttons, or they dont seem to do anything
> 

Is pikrellcam running?  At first install you need to open System and click "Start".  If you enabled auto start
in the install then pikrellcam will auto start on subsequent boots.

If there's still a problem, open a terminal and run "pikrellcam" and then "pikrellcam -v" to look at
possible error messages.  Also in the web interface do you see log lines if you click System->Log?

**Comment by rcpilotp51** [comment]
Thanks i reinstalled using the user pi...my created user didnt work...thanks

**Comment by rcpilotp51** [comment]
going to close this: others should do the following 

- install raspian (not lite)

- secure user "pi"
- update 
-configure camera and resolution
- install pikrellcam
- enjoy
